/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DisplayCard: typeof import('./components/display-card/DisplayCard.vue')['default']
    FlexGroup: typeof import('./components/flex-group/FlexGroup.vue')['default']
    FlexGroupItem: typeof import('./components/flex-group/FlexGroupItem.vue')['default']
    Footer: typeof import('./components/footer/Footer.vue')['default']
    FormInputButton: typeof import('./components/forms/FormInputButton.vue')['default']
    FormInputCheckbox: typeof import('./components/forms/FormInputCheckbox.vue')['default']
    FormInputCheckboxMultipleWrapper: typeof import('./components/forms/FormInputCheckboxMultipleWrapper.vue')['default']
    FormInputCheckboxWrapper: typeof import('./components/forms/FormInputCheckboxWrapper.vue')['default']
    FormInputText: typeof import('./components/forms/FormInputText.vue')['default']
    FormInputTextWrapper: typeof import('./components/forms/FormInputTextWrapper.vue')['default']
    FormInputtText: typeof import('./components/forms/FormInputtText.vue')['default']
    FormInputWrapper: typeof import('./components/forms/FormInputWrapper.vue')['default']
    Header: typeof import('./components/header/Header.vue')['default']
    HeaderNavigation: typeof import('./components/header-navigation/HeaderNavigation.vue')['default']
    LayoutRow: typeof import('./components/layout-row/LayoutRow.vue')['default']
    LocaleSwitcher: typeof import('./components/locale-switcher/LocaleSwitcher.vue')['default']
    MultiStepForm: typeof import("./components/multi-step-form.vue")["default"]
    MultiStepFormStep1: typeof import('./components/multi-step-form/MultiStepFormStep1.vue')['default']
    MultiStepFormStep2: typeof import('./components/multi-step-form/MultiStepFormStep2.vue')['default']
    MultiStepFormStep3: typeof import('./components/multi-step-form/MultiStepFormStep3.vue')['default']
    PageRow: typeof import('./components/page-row/PageRow.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionParallax: typeof import('./components/section-parallax/SectionParallax.vue')['default']
    SimpleGrid: typeof import('./components/simple-grid/SimpleGrid.vue')['default']
    SimpleGridItem: typeof import('./components/simple-grid/SimpleGridItem.vue')['default']
  }
}
