/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    FunctionalFooterFooter: typeof import('./components/functional/footer/Footer.vue')['default']
    FunctionalHeaderHeader: typeof import('./components/functional/header/Header.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScaffoldingFlexGroupFlexGroup: typeof import('./components/scaffolding/flex-group/FlexGroup.vue')['default']
    ScaffoldingFlexGroupFlexGroupItem: typeof import('./components/scaffolding/flex-group/FlexGroupItem.vue')['default']
    ScaffoldingLayoutRowLayoutRow: typeof import('./components/scaffolding/layout-row/LayoutRow.vue')['default']
    ScaffoldingSimpleGridSimpleGrid: typeof import('./components/scaffolding/simple-grid/SimpleGrid.vue')['default']
    ScaffoldingSimpleGridSimpleGridItem: typeof import('./components/scaffolding/simple-grid/SimpleGridItem.vue')['default']
  }
}
